-- Initial site settings row (only if empty)
INSERT INTO public.site_settings (
    company_name,
    tagline,
    email,
    phone,
    phone_alt,
    whatsapp,
    address,
    copyright_text
)
SELECT
    'Maple Consulting Engineers',
    'Civil & Structural Engineering Consultancy',
    'maplececlt@gmail.com',
    '+91 8281 33 44 35',
    '+91 9946 62 50 63',
    '+91 8281 33 44 35',
    'Near Popular Vehicle Showroom, Meleparamba, Calicut',
    '© 2026 Maple Consulting Engineers. All rights reserved.'
WHERE NOT EXISTS (SELECT 1 FROM public.site_settings);

-- Initial homepage content skeleton row (only if empty)
INSERT INTO public.homepage_content (
    hero_eyebrow,
    hero_title_line1,
    hero_title_line2,
    hero_description,
    hero_cta_label,
    hero_cta_url,
    hero_vertical_text,
    about_section_number,
    about_eyebrow,
    about_title,
    about_description_1,
    about_description_2,
    about_cta_label,
    about_cta_url,
    vision_eyebrow,
    vision_title,
    purpose_eyebrow,
    purpose_title_line1,
    purpose_title_line2,
    purpose_tagline,
    services_section_number,
    services_eyebrow,
    services_title,
    services_tagline,
    team_section_number,
    team_eyebrow,
    team_title,
    team_quote,
    team_cta_label,
    team_cta_url,
    clients_section_number,
    clients_eyebrow,
    clients_title,
    clients_tagline,
    projects_section_number,
    projects_eyebrow,
    projects_title,
    projects_description,
    projects_cta_label,
    projects_cta_url,
    contact_section_number,
    contact_eyebrow,
    contact_title,
    contact_highlight_text
)
SELECT
    E'ENGINEERING\nPEOPLE\nPLACES\nBETTER TOMORROW',
    'delivering',
    'EXCELLENCE',
    'Every project is an opportunity to build upon our reputation for quality, creativity, and strong relationships.',
    'DISCOVER MAPLE',
    '#about',
    'CIVIL & STRUCTURAL ENGINEERING',
    '01',
    'ABOUT US',
    E'Built on experience.\nDriven by possibility.',
    'Maple consulting engineers are a Civil and Structural Engineering consultancy offering a nationwide service to our clients. Our experience and expertise allow us to offer a range of specialist services, all integrated to serve the needs and requirements of clients in the sectors in which we operate. We provide innovative structural design and analysis services to architects, owners, and developers for all types of buildings at all project phases.',
    'Maple consulting engineers undertakes a wide variety of work, ranging from major new build schemes through to complex renovation projects across the market sectors in which we operate. We are involved in consulting projects across both the public and private sectors.',
    'MORE ABOUT US',
    '#contact',
    'OUR VISION',
    E'Shaping A\nBetter World',
    'OUR PURPOSE',
    'NURTURING',
    'GROWTH',
    'PEOPLE STRUCTURED COMMUNITIES A RENOWNED TOMORROW',
    '02',
    'SERVICES',
    'What we do.',
    'IDEAS STRUCTURES EXECUTING FOR A BETTER TOMORROW',
    '03',
    'TEAM',
    E'Our people\nare our company.',
    'Expertise becomes meaningful when it is shared.',
    'MEET OUR TEAM',
    '#team',
    '04',
    'CLIENTS',
    'Our clients are our growth.',
    E'TRUSTED COLLABORATIONS\nLONG TERM RELATIONSHIPS',
    '05',
    'PROJECTS',
    'Every Project is Unique',
    'We approach every design challenge with a passion for solving problems. Our goal is to provide good quality works and services in everything we do.',
    'VIEW ALL PROJECTS',
    '/projects',
    '06',
    'CONTACT',
    E'We are looking\nforward to the future.',
    E'Wherever!\nWhenever!\nTogether with you.'
WHERE NOT EXISTS (SELECT 1 FROM public.homepage_content);
